### PR TITLE
Update Security Architecture.md

### PR DESCRIPTION
**Pull request by ChadFong**
Correct grammar and spelling

### CODE REVIEW

**Comment by lukos** [comment]
Hi Chad. Try not to be too picky on spellings. Some of the words you have "corrected" are spelled in British English and are not spelled incorrectly. Your change from "which" to "that" although correct, would have been more correct if you had simply put a comma before "which".

**Comment by bradchesney79** [comment]
Good catch on authetnication though.

There's this island, https://en.wikipedia.org/wiki/Hans_Island , where the Danes and Canadians have a amicable dispute. Something about leaving Delicious Maple Syrup & Classy Alcoholic beverages for the next person in over some kind of disagreement that isn't so important.

I would like to encourage the same here. If a British English person writes or appends-- then I imagine the text will use British English. Or when I am in there actually doing something, I may change them to American English or sometimes I switch my wording to be dialect ambivalent and the words are all the same between the two-- like avoiding -izatio/-isation or -or/-our in in my word choices. There are so many words to choose from without losing the greater meaning or even little connotations.

What I would like to discourage is combing the text and making what amounts to dialect changes-- without discouraging participation. @vdbaan do you have an opinion?

**Comment by bradchesney79** [comment]
My bigger concern is why this couldn't be safely merged. Eh, I just changed to public transportation so I just gained ~6 hours a week to look at this more.

**Comment by vdbaan** [comment]
I believe that for now this is a 'non-issue', lets first focus on the content and do the Eglish/american translation later.

**Comment by bradchesney79** [comment]
I'm being lazy and just fixing the one error that exists as of now and creating a clean pull request. Closing this pull request that 'needs merged'. Regardless, thanks @ChadFong for the second set of eyes, good catch.

**Pull request closed without merging**
