### PR TITLE
Add semicolon, thus separating propositions. Move the last sentence t…

### PR DESCRIPTION
**Pull request by ner0x652**
…o a new line

### CODE REVIEW

**Comment by bradchesney79** [comment]
I don't know who you are-- but thank you. Contributions reviewed and found beneficial.

**Comment by ner0x652** [comment]
:) With pleasure. Other contributions will follow (hope beneficial). 

Thank you, too!

**Comment by ner0x652** [comment]
@bradchesney79 what is the state of the project? (I see a lot of unfinished sections)

**Comment by bradchesney79** [comment]
I contributed most during my lunch break at my last job. But, the new job, three kids, and just constant random assaults on my schedule have made it harder for me to spend as much time as I would like. The status is that, I haven't been a very good leader. But, I try to keep an eye on things so commits don't get stale and any contributors know their work is valued.

**Pull request merged**
